
package proyecto;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;


public class Principal extends javax.swing.JFrame {
    public static CarteraClientes cc = new CarteraClientes();
    public static DefaultComboBoxModel cboDNI = new DefaultComboBoxModel();
    DefaultComboBoxModel cboCod = new DefaultComboBoxModel();
    DefaultListModel lstPre = new DefaultListModel();
    DefaultListModel lstCod = new DefaultListModel();
    DefaultListModel lstNom = new DefaultListModel();
    DefaultListModel lstDias = new DefaultListModel();
    DefaultListModel lstPrecioParcial = new DefaultListModel();
    private final String[] Videos={"50 Sombras de Grey","American Pie","La chica de a lado","Proyecto X"};
    private final double[] Precios={7,5,6,3};
    private final int[] Codigos = {100,101,102,103};
    double cont=0;
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        Date fecha = new Date();
        DateFormat df = DateFormat.getTimeInstance(DateFormat.MEDIUM);
        DateFormat dh = DateFormat.getDateInstance(DateFormat.MEDIUM);
        lblFecha.setText(df.format(fecha));
        lblHora.setText(dh.format(fecha));
        for(int i=0;i<4;i++){
            cboCod.addElement(Codigos[i]);
        }
        cboCodVid.setModel(cboCod);
        txtNomVideo.setText(Videos[0]);
        txtPrecioVid.setText(String.valueOf(Precios[0]));
        if(cboDniClie.getModel().getElementAt(0).toString().equalsIgnoreCase("Item 1")){
            cboDniClie.setModel(cboDNI);
        }
        if(lstCodVid.getModel().getElementAt(0).toString().equalsIgnoreCase("Item 1")){
            lstCodVid.setModel(lstCod);
            lstNumeroDias.setModel(lstPre);
            lstNomVid.setModel(lstNom);
            lstPrecioDias.setModel(lstDias);
        }
        if(lstPrecioTotal.getModel().getElementAt(0).toString().equalsIgnoreCase("Item 1")){
            lstPrecioTotal.setModel(lstPrecioParcial);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBien = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cboDniClie = new javax.swing.JComboBox();
        txtNomClie = new javax.swing.JTextField();
        txtApeClie = new javax.swing.JTextField();
        btnNuevoClie = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cboCodVid = new javax.swing.JComboBox();
        txtPrecioVid = new javax.swing.JTextField();
        txtNomVideo = new javax.swing.JTextField();
        txtDias = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCodVid = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstNomVid = new javax.swing.JList();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstNumeroDias = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstPrecioDias = new javax.swing.JList();
        btnEliminar = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstPrecioTotal = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lblBien.setText("Bienvenido");

        lblFecha.setText("Bienvenido");

        lblHora.setText("Bienvenido");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        cboDniClie.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboDniClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboDniClieActionPerformed(evt);
            }
        });

        btnNuevoClie.setText("Nuevo");
        btnNuevoClie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoClieActionPerformed(evt);
            }
        });

        jLabel11.setText("DNI:");

        jLabel12.setText("Nombre:");

        jLabel13.setText("Apellido:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboDniClie, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtNomClie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtApeClie, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoClie)
                        .addGap(29, 29, 29))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboDniClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApeClie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNuevoClie))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Videos"));

        cboCodVid.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cboCodVid.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboCodVidItemStateChanged(evt);
            }
        });

        txtPrecioVid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtPrecioVid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioVidActionPerformed(evt);
            }
        });

        txtNomVideo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Video:");

        jLabel2.setText("Codigo");

        jLabel3.setText("Precio/dia");

        jLabel4.setText("Nº dias:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(cboCodVid, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txtNomVideo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPrecioVid, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnAgregar))
                    .addComponent(jLabel4))
                .addGap(29, 29, 29))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtDias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecioVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cboCodVid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomVideo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        lstCodVid.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstCodVid.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstCodVidValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(lstCodVid);

        lstNomVid.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNomVid.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNomVidValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstNomVid);

        lstNumeroDias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstNumeroDias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstNumeroDiasValueChanged(evt);
            }
        });
        jScrollPane3.setViewportView(lstNumeroDias);

        lstPrecioDias.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPrecioDias.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPrecioDiasValueChanged(evt);
            }
        });
        jScrollPane4.setViewportView(lstPrecioDias);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lstPrecioTotal.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        lstPrecioTotal.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstPrecioTotalValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(lstPrecioTotal);

        jLabel5.setText("Codigo:");

        jLabel6.setText("Video:");

        jLabel7.setText("Precio/dia:");

        jLabel8.setText("Nº dias:");

        jLabel9.setText("Precio Total:");

        txtTotal.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel10.setText("TOTAL:");

        jButton1.setText("Generar Boleta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblFecha)
                        .addGap(28, 28, 28)
                        .addComponent(lblHora)
                        .addGap(62, 62, 62))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel7)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)))
                        .addComponent(btnEliminar)
                        .addGap(33, 33, 33))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBien)
                    .addComponent(lblFecha)
                    .addComponent(lblHora))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel6))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel9)
                        .addComponent(jLabel8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoClieActionPerformed
        NuevoCliente nc = new NuevoCliente(this, rootPaneCheckingEnabled);
        nc.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnNuevoClieActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
if(txtDias.getText().trim().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(this, "Debes colocar dias."," "+ " Validacion",JOptionPane.ERROR_MESSAGE);
        }else{
        boolean b=false;
        for(int i=0; i<lstCodVid.getModel().getSize();i++){
        if(cboCodVid.getSelectedItem().toString().equalsIgnoreCase(lstCodVid.getModel().getElementAt(i).toString())){
            JOptionPane.showMessageDialog(this, "El codigo ya existe","Validacion",JOptionPane.ERROR_MESSAGE);
            b=true;
            break;
            
        }
        }
        if(b==false){
            
            double m;
            int ind= cboCodVid.getSelectedIndex();
            lstCod.addElement(cboCodVid.getSelectedItem());
            lstNom.addElement(txtNomVideo.getText());
            m= Double.valueOf(txtPrecioVid.getText())* Double.valueOf(txtDias.getText());
            lstPre.addElement(Double.valueOf(txtPrecioVid.getText()));
            lstDias.addElement(txtDias.getText());
            lstPrecioParcial.addElement(m);
            lstCodVid.setModel(lstCod);
            lstNomVid.setModel(lstNom);
            lstNumeroDias.setModel(lstPre);
            lstPrecioDias.setModel(lstDias);
            lstPrecioTotal.setModel(lstPrecioParcial);
            
            cont = cont + m;
            txtTotal.setText(String.valueOf(cont) );
            lstCodVid.setSelectionMode(ind);
        }
        }
        
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void cboCodVidItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboCodVidItemStateChanged
        int in = cboCodVid.getSelectedIndex();
        if(in>=0){
            txtNomVideo.setText(Videos[in]);
            txtPrecioVid.setText(String.valueOf(Precios[in]));
            
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_cboCodVidItemStateChanged

    private void lstCodVidValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstCodVidValueChanged

        int index = lstCodVid.getSelectedIndex();
        if(index>=0){
            lstNomVid.setSelectedIndex(index);
            lstNumeroDias.setSelectedIndex(index);
            lstPrecioDias.setSelectedIndex(index);
            lstPrecioTotal.setSelectedIndex(index);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lstCodVidValueChanged

    private void lstNomVidValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNomVidValueChanged

        int index = lstNomVid.getSelectedIndex();
        if(index>=0){
            lstCodVid.setSelectedIndex(index);
            lstNumeroDias.setSelectedIndex(index);
            lstPrecioDias.setSelectedIndex(index);
            lstPrecioTotal.setSelectedIndex(index);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_lstNomVidValueChanged

    private void lstPrecioDiasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPrecioDiasValueChanged

        int index = lstPrecioDias.getSelectedIndex();
        if(index>=0){
            lstNomVid.setSelectedIndex(index);
            lstNumeroDias.setSelectedIndex(index);
            lstCodVid.setSelectedIndex(index);
            lstPrecioTotal.setSelectedIndex(index);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_lstPrecioDiasValueChanged

    private void lstNumeroDiasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstNumeroDiasValueChanged
        int index = lstNumeroDias.getSelectedIndex();
        if(index>=0){
            lstNomVid.setSelectedIndex(index);
            lstCodVid.setSelectedIndex(index);
            lstPrecioDias.setSelectedIndex(index);
            lstPrecioTotal.setSelectedIndex(index);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_lstNumeroDiasValueChanged

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int inde=lstCodVid.getSelectedIndex();
        if(inde>=0){
            lstPre.removeElementAt(inde);
            lstNom.removeElementAt(inde);
            lstCod.removeElementAt(inde);
            lstDias.removeElementAt(inde);
            double e= Double.valueOf(lstPrecioParcial.getElementAt(inde).toString());
            lstPrecioParcial.removeElementAt(inde);
            cont = cont-e;
            lstCodVid.setModel(lstCod);
            lstNomVid.setModel(lstNom);
            lstNumeroDias.setModel(lstPre);
            lstPrecioDias.setModel(lstDias);
            lstPrecioTotal.setModel(lstPrecioParcial);
            String r = String.valueOf(cont);
            txtTotal.setText(r);
            
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void cboDniClieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboDniClieActionPerformed

        int ind = cboDniClie.getSelectedIndex();
        if(ind>=0){
            txtNomClie.setText(cc.obtenerCliente(ind).getNombres());
            txtApeClie.setText(cc.obtenerCliente(ind).getApellidos());
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_cboDniClieActionPerformed

    private void lstPrecioTotalValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstPrecioTotalValueChanged
                int index = lstPrecioTotal.getSelectedIndex();
        if(index>=0){
            lstNomVid.setSelectedIndex(index);
            lstCodVid.setSelectedIndex(index);
            lstPrecioDias.setSelectedIndex(index);
            lstNumeroDias.setSelectedIndex(index);
        }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_lstPrecioTotalValueChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        Boleta bol = new Boleta(this, rootPaneCheckingEnabled);
        bol.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtPrecioVidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioVidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioVidActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnNuevoClie;
    private javax.swing.JComboBox cboCodVid;
    public static javax.swing.JComboBox cboDniClie;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    public static javax.swing.JLabel lblBien;
    public static javax.swing.JLabel lblFecha;
    public static javax.swing.JLabel lblHora;
    public static javax.swing.JList lstCodVid;
    public static javax.swing.JList lstNomVid;
    public static javax.swing.JList lstNumeroDias;
    public static javax.swing.JList lstPrecioDias;
    public static javax.swing.JList lstPrecioTotal;
    public static javax.swing.JTextField txtApeClie;
    private javax.swing.JTextField txtDias;
    public static javax.swing.JTextField txtNomClie;
    private javax.swing.JTextField txtNomVideo;
    private javax.swing.JTextField txtPrecioVid;
    public static javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
